holin/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
admin.autodiscover()

from app import views 
    

    
urlpatterns = patterns('',
    url(r'^site_edit/$', login_required(views.GalleryList.as_view()), name='file_upload_admin'),
    url(r'^category_add/$', views.AddCategory.as_view(), name='add_category'),
    url(r'^zip_upload/$', views.ZipUpload.as_view(), name = 'zip_upload_url'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',name="my_login"),
    # url(r'^add/$', views.AddGallery.as_view(), name='add'),

    url(r'^image_gallery/', include('image_gallery.urls', namespace='image_gallery')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^get_pics/$', views.get_pics),
    
    url(r'^send-me-a-message/$', views.send_me_amessage),
    
    url(r'^$', views.main_page),
    
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

image_gallery/urls.py
from django.conf.urls import *
# from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from views import *

urlpatterns = patterns('',
    url(r'^upload/$', Upload.as_view(), name='upload'),
    url(r'^delete/$', Delete.as_view(), name='delete'),
    
)

image_gallery/models.py
import os
from django.db import models
from django.contrib.auth.models import User

from image_gallery import settings


class GalleryImage(models.Model):

    image = models.ImageField(upload_to=settings.GALLERY_DIR)
    thumbnail = models.ImageField(upload_to=os.path.join(settings.GALLERY_DIR, 'thumbnails'))
    creation_time = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, blank=True, null=True)
    orientation = models.NullBooleanField(default=False)

image_gallery/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _
from image_gallery.widgets import GalleryWidget


class GalleryFormField(forms.ModelMultipleChoiceField):
    default_error_messages = {
        'image_count': (_(u'Too many images'))
    }

    def __init__(self, queryset, cache_choices=False, required=True,
                     widget=None, label=None, initial=None,
                     help_text=None, *args, **kwargs):
        self.max_images = kwargs.pop('max_images')
        widget = GalleryWidget(attrs={'max_images': self.max_images, })
        super(GalleryFormField, self).__init__(queryset,
                cache_choices, required, widget, label, initial, help_text,
                *args, **kwargs)

    def clean(self, value):
        value = value.split(',') if value else []
        if self.max_images and len(value) > self.max_images:
            raise ValidationError(self.error_messages['image_count'])
        return super(GalleryFormField, self).clean(value)

image_gallery/views.py
# -*- coding: utf-8 -*-
import imghdr
import json
import os

from django.core.files import File
from django.http import HttpResponse
from django.views.generic.base import View
from django.utils.translation import ugettext as _
from PIL import Image

from image_gallery import settings
from image_gallery.models import GalleryImage

from utils import change_form_filenames
from utils import sizeof_fmt


class Upload(View):
    def post(self, request):
        response = {'success': False, }
        img = None
        if request.user.is_authenticated() or not settings.GALLERY_LOGIN_REQUIRED:
            file = (change_form_filenames(request.FILES)).get('image_gallery-file')
            if file:
                img = GalleryImage()
                img.image = file
                if img.image.width > img.image.height :
                    #LANDSCAPE
                    orientation = False
                else:
                    orientation = True
                img.orientation = orientation
                
                if request.user.is_authenticated():
                    img.owner = request.user
                img.save()

                img.thumbnail.save(os.path.basename(img.image.path), File(open(img.image.path)))
                thumb = Image.open(img.image.path)
                (w, h) = thumb.size
                side = min(w, h)
                thumb = thumb.crop([(w - side) / 2, (h - side) / 2, (w + side) / 2, (h + side) / 2])
                thumb.thumbnail(settings.GALLERY_THUMBNAILS_SIZE, Image.ANTIALIAS)
                thumb.save(img.thumbnail.path, quality=100)
                img.save()

                fsize = img.image.size
                
                max_fsize = settings.GALLERY_MAX_FILE_SIZE
                if fsize <= max_fsize:
                    type = imghdr.what(img.image.path).upper()
                    allowed_types = settings.GALLERY_IMAGE_TYPES
                    if type in allowed_types:
                        pil_img = Image.open(img.image.path)
                        min_size = settings.GALLERY_MIN_IMAGE_SIZE
                        max_size = settings.GALLERY_MAX_IMAGE_SIZE
                        if pil_img.size[0] >= min_size[0] and pil_img.size[1] >= min_size[1]:
                            if pil_img.size[0] <= max_size[0] and pil_img.size[1] <= max_size[1]:
                                response['success'] = True
                                response['id'] = img.id
                                response['url'] = img.thumbnail.url
                            else:
                                response['message'] = _('Maximal image size is %(w)sx%(h)s (Your image size is %(w_)sx%(h_)s).') % {'w': max_size[0], 'h': max_size[1], 'w_': pil_img.size[0], 'h_': pil_img.size[1]}
                        else:
                            response['message'] = _('Minimal image size is %(w)sx%(h)s (Your image size is %(w_)sx%(h_)s).') % {'w': min_size[0], 'h': min_size[1], 'w_': pil_img.size[0], 'h_': pil_img.size[1]}
                    else:
                        response['message'] = _('Unsupported image format. Supported formats are %s') % ', '.join(allowed_types).upper()
                else:
                    response['message'] = _('Maximal image file size is %s') % sizeof_fmt(max_fsize)
            else:
                response['message'] = _('Can not upload image. Please try again.')
        else:
            response['message'] = _('You must authorize to upload image.')

        if response['success'] == False and img is not None:
            img.delete()
        return HttpResponse(json.dumps(response))

class Delete(View):
    def post(self, request):
        response = {'success':False }
        id = request.POST.get('id')
        if id:
            img = GalleryImage.objects.get(id=id)
            
            if img.owner == request.user or request.user.is_superuser or img.owner is None:
                img.image.delete()
                img.thumbnail.delete()
                img.delete()
                
                response['success'] = True
        return HttpResponse(json.dumps(response))

image_gallery/templates/image_gallery/gallery.html
{% load i18n %}
{% load staticfiles %}

<input {% if max_images %}max_images="{{ max_images }}"{% endif %} type="file" id="{{ id }}-file" name="image_gallery-file" onChange="GalleryImageChange('{{ id }}')">

<div class="alert alert-error" id="{{ id }}-errors-block" style="display: none">
    <button class="close" data-dismiss="alert">×</button>
    <p><strong>{% trans "Image upload error:" %} </strong></p>
    <hr/>
    <p id="{{ id }}-errors-text"></p>
</div>

<div class="gallery" id="{{ id }}-thumbnails"><br/>
    <img class="gallery-image img-rounded" id="{{ id }}-loading" src="{% static "image_gallery/img/ajax-loader.gif" %}" style="display:none">
    <span class="button-delete btn btn-mini" style="display:none">
        <img src="{% static "image_gallery/img/deleteImage.png" %}"/>
    </span>
    {% for img in images %}
	
        <div class="gallery-image" id="{{ id }}-div{{ img.id }}" onclick="GalleryImageDelete('{{ id }}', '{{ img.id }}')" onmouseover="showButton('{{ id }}', '{{ img.id }}')" onmouseout="hideButton('{{ id }}', '{{ img.id }}')">
            <div>
				
                <img id="{{ id }}-img{{ img.id }}" src="{{ img.src }}">
            </div>
        </div>
    {% endfor %}
</div>


<script type="text/javascript">

    initGallery( '{% url 'image_gallery:upload' %}', '{% url 'image_gallery:delete' %}', '{% url 'add_category' %}', '{% url 'zip_upload_url' %}')
    showFileButton('{{ id }}');
</script>

image_gallery/templates/image_gallery/show_gallery.html
{% comment %}

		        html = '<div class="gallery-image" 
                             onclick="GalleryImageDelete(\''+id+'\', \''+response.id+'\')"
                             onmouseover="showButton(\''+id+'\', \''+response.id+'\')"
                             onmouseout="hideButton(\''+id+'\', \''+response.id+'\')">'
		        html += '<div><img id="'+id+'-img'+response.id+'" src="'+response.url+'"></div>'

{% endcomment %}


{% if gallery.all %}
    <div class="gallery">
    {% for img in gallery.all %}
	
	<div style='float:left'>
				<a class="gallery-image hover-lighting thumbnail" href="{{ img.image.url }}" rel="prettyPhoto[id{{ prettyPhoto_id }}]" >
		
				<img class='image-thumbnail img-rounded' src="{{ img.thumbnail.url }}">
			
			</a>
			<div>
			<input class='remove-button btn btn-mini' img_id='{{img.id}}' type='button'>
			
		</div>
	</div>	
    {% endfor %}
    </div>

{% endif %}